##### Logistic Regression
- it uses sigmoid function
- binomial classification(target has only 2 classes)
- multinomial(more than 2 classes)

In [1]:
import pandas as pd
df=pd.read_csv("heartdisease.csv")
df.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [2]:
df.isna().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [4]:
import numpy as np
df["Ca"]=df["Ca"].replace(np.nan,0.0)
df["Thal"]=df["Thal"].replace(np.nan,'normal')

In [5]:
df.isna().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df["ChestPain"]=le.fit_transform(df["ChestPain"])
df["Thal"]=le.fit_transform(df["Thal"])
df["AHD"]=le.fit_transform(df["AHD"])
df.head()

Unnamed: 0  Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
0           1   63    1          3     145   233    1        2    150      0   
1           2   67    1          0     160   286    0        2    108      1   
2           3   67    1          0     120   229    0        2    129      1   
3           4   37    1          1     130   250    0        0    187      0   
4           5   41    0          2     130   204    0        2    172      0   

   Oldpeak  Slope   Ca  Thal  AHD  
0      2.3      3  0.0     0    0  
1      1.5      2  3.0     1    1  
2      2.6      2  2.0     2    1  
3      3.5      3  0.0     1    0  
4      1.4      1  0.0     1    0

In [11]:
y=df["AHD"]
x=df.iloc[:,1:14]
x.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0   63    1          3     145   233    1        2    150      0      2.3   
1   67    1          0     160   286    0        2    108      1      1.5   
2   67    1          0     120   229    0        2    129      1      2.6   
3   37    1          1     130   250    0        0    187      0      3.5   
4   41    0          2     130   204    0        2    172      0      1.4   

   Slope   Ca  Thal  
0      3  0.0     0  
1      2  3.0     1  
2      2  2.0     2  
3      3  0.0     1  
4      1  0.0     1

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=25)
x_train.head()


Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
1     67    1          0     160   286    0        2    108      1      1.5   
142   52    1          2     128   205    1        0    184      0      0.0   
126   56    0          0     200   288    1        2    133      1      4.0   
37    57    1          0     150   276    0        2    112      1      0.6   
275   64    1          3     170   227    0        2    155      0      0.6   

     Slope   Ca  Thal  
1        2  3.0     1  
142      1  0.0     1  
126      3  2.0     2  
37       2  1.0     0  
275      2  0.0     2

In [25]:
x_train.shape

(242, 13)

In [26]:
x_test.shape

(61, 13)

In [27]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
x_test.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
281   47    1          1     130   253    0        0    179      0      0.0   
81    53    0          0     130   264    0        2    143      0      0.4   
40    65    0          0     150   225    0        2    114      0      1.0   
175   57    1          0     152   274    0        0     88      1      1.2   
58    54    1          1     125   273    0        2    152      0      0.5   

     Slope   Ca  Thal  
281      1  0.0     1  
81       2  0.0     1  
40       2  3.0     2  
175      2  1.0     2  
58       3  1.0     1

In [29]:
model.predict([[51,0,0,130,305,0,0,142,1,1.2,2,0.0,2]])

array([1])

In [32]:
y_test

281    0
81     0
40     1
175    1
58     0
105    0
222    0
251    1
153    1
149    0
213    1
91     1
218    0
179    0
228    1
48     0
186    0
282    1
4      0
31     1
45     1
97     1
66     1
236    1
226    0
120    1
12     1
155    1
223    1
254    0
      ..
279    0
19     0
104    1
247    1
210    0
18     0
159    0
204    0
208    0
23     1
6      1
207    1
87     0
158    1
121    1
154    1
287    0
102    0
68     1
198    0
277    0
169    0
84     0
56     1
232    1
285    1
294    1
133    0
196    0
75     0
Name: AHD, Length: 61, dtype: int32

In [30]:
y_predict=model.predict(x_test)
y_predict

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0])

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))

0.8852459016393442
[[26  5]
 [ 2 28]]


#### Support Vector Machine(SVM)
- more accuracy and less computation power

In [39]:
from sklearn.datasets import load_iris
iris=load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [40]:
iris.filename

'C:\\Users\\Public\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv'

In [42]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [45]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["outcome"]=iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   outcome  
0        0  
1        0  
2        0  
3        0  
4        0

In [48]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
outcome              0
dtype: int64

In [53]:
#start:end:step
#iloc[rows,col]
x=df.iloc[:,0:4]
y=df["outcome"]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [54]:
x_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
15                5.7               4.4                1.5               0.4
65                6.7               3.1                4.4               1.4
11                4.8               3.4                1.6               0.2
42                4.4               3.2                1.3               0.2

In [55]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [56]:
y_predict=model.predict(x_test)
y_predict

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [57]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_predict))
print(confusion_matrix(y_test,y_predict))

1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
